#!/bin/sh
#
# 	supercal: displays cals, accepting ranges of months and years
#
#	usage: supercal [month [ - range ]] [year]
#  errors: exit 1, no args provided
#		   exit 2, no end month to pass to ./get_range
#          exit 3, error from ./name2num (via ./get_range)
#		   exit 4, invalid input, not a valid year
#

#
# a function to report errors: takes a string and an exit value
# Copied from make-backups4 from assignment page (author Bruce Molay)
#
oops()
{
    echo "$0: $1"
    exit $2
}

# do we have at least one arg (month or year)
if [ $# = 0 ]
then
    oops "usage: $0 [month [ - range ]] [year]" 1
fi

# initialize an empty list and year
LIST=""
Y=""

while [ $# -gt 0 ]
do
    # handle a potential range
    if [ "$2" = "-" ]
    then
        # check if there is an ending month to pass through
        if [ ! $3 ]
        then
            oops "there is no end month, try again" 2
        # get months from $1 - $3 (start - end)
        elif LIST="$LIST $(./get_range $1 $3)"
        then
            shift 2
        # there was an error reading either $1 or $3
        else
            oops "./name2num didn't read a valid month, try again" 3
        fi
    # if no range, try reading a month
    elif M=$(./name2num $1)
    then
        LIST="$LIST $M"

        # if not a month, try reading a year by
        # searching for any non-digits present in $1
        elif $(echo $1 | grep -q '[^0-9]')
        then
            oops "there was an invalid year, try again" 4
        else
            Y=$1
        fi

        # print the calendar(s)
        if [ $Y ]			# we have a year specified
        then
            ./print_cal $Y $LIST	# print the months for given $Y
					# if $LIST is empty, ./print_cal
					# will fill in all months

            LIST=""			# clear for more args (new year)
            Y=""			# clear for more args
        fi

        shift
done

# no year was found by the end, print the months found with current year
if [ "$LIST" -a ! $Y ]
then
    ./print_cal $(date +"%Y") $LIST
fi

exit 0
